---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
    groups:
      actions-deps:
        patterns:
          - '*'
  - package-ecosystem: 'mix'
    directory: '/'
    schedule:
      interval: daily
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
  - package-ecosystem: 'mix'
    directory: '/example'
    schedule:
      interval: daily
    groups:
      all-dependencies:
        patterns:
          - '*'
